Stop using bare except: statements
It is almost never a good idea to catch all exceptions, and then do
nothing about them. This patch logs all caught exceptions so that the
user has some possibilty to debug what is happening.

Also, make ./check check for bare excepts and fail the test suite if it
finds anything.

diff --git a/check b/check
--- a/check
+++ b/check
@@ -126,6 +126,11 @@ then
                     echo "ERROR: $x has a hashbang" 1>&2
                     errors=1
                 fi
+                if grep except: "$x"
+                then
+                    echo "ERROR: $x has a bare except:" 1>&2
+                    errors=1
+                fi
                 ;;
         esac
     done
