Install licensecheck.pl with morphlib
Change-Id: If1b156a309236956d7a35136db35a8fd0ab3ad71

diff --git a/scripts/check-silliness b/scripts/check-silliness
--- a/scripts/check-silliness
+++ b/scripts/check-silliness
@@ -19,17 +19,23 @@
 errors=0
 
 for x; do
-    if tr -cd '\t' < "$x" | grep . > /dev/null
-    then
-        echo "ERROR: $x contains TAB characters" 1>&2
-        grep -n -F "$(printf "\t")" "$x" 1>&2
-        errors=1
-    fi
+    case "$x" in
+        morphlib/licensecheck.pl) ;;
+        *)
+            if tr -cd '\t' < "$x" | grep . > /dev/null
+            then
+                echo "ERROR: $x contains TAB characters" 1>&2
+                grep -n -F "$(printf "\t")" "$x" 1>&2
+                errors=1
+            fi
+            ;;
+    esac
 
     case "$x" in
         # Excluding yarn files since it's not possible to split up the
         # IMPLEMENTS lines of them
         *.yarn) ;;
+        morphlib/licensecheck.pl) ;;
         *)
             if awk 'length($0) > 79' "$x" | grep . > /dev/null
             then
